### ISSUE TITLE
Is the problem database considered part of the repo?

### ISSUE THREAD

**Issue by StanislavNikolov** [espr1t/action#6]
I was wondering if the database (obviously not the parts related to user data / authentication) is public. If not, may I suggest ""open sourcing"" it :D. I'm specifically interested problem statements, tests, checkers and tags.

**Comment by espr1t** [comment]
No, I've considered this but for now they are private. I may reconsider in the future, I have weighed the PROs and CONs several times already, thus at some point I may do it.

At least the tags will soon be exposed in a easier-to-search way in the system.
